[package]
name = "radicle"
license = "MIT OR Apache-2.0"
version = "0.2.0"
authors = ["Alexis Sellier <alexis@radicle.xyz>"]
edition = "2021"

[features]
default = []
test = ["quickcheck"]
sql = ["sqlite"]

[dependencies]
automerge = { version = "0.1" }
base64 = { version= "0.13" }
byteorder = { version = "1.4" }
crossbeam-channel = { version = "0.5.6" }
ed25519-compact = { version = "2.0.2", features = ["pem"] }
fastrand = { version = "1.8.0" }
git-ref-format = { version = "0", features = ["serde", "macro"] }
multibase = { version = "0.9.1" }
log = { version = "0.4.17", features = ["std"] }
once_cell = { version = "1.13" }
olpc-cjson = { version = "0.1.1" }
sha2 = { version = "0.10.2" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
siphasher = { version = "0.3.10" }
radicle-git-ext = { version = "0", features = ["serde"] }
sqlite = { version = "0.28.1", optional = true }
nonempty = { version = "0.8.0", features = ["serialize"] }
tempfile = { version = "3.3.0" }
thiserror = { version = "1" }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "serde"] }
zeroize = { version = "1.5.7" }

[dependencies.git2]
version = "0.15.0"
default-features = false
features = ["vendored-libgit2"]

[dependencies.radicle-cob]
path = "../radicle-cob"
version = "0"

[dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0"
features = ["git-ref-format", "ssh", "sqlite"]

[dependencies.radicle-ssh]
path = "../radicle-ssh"
version = "0"
default-features = false

[dependencies.quickcheck]
version = "1"
default-features = false
optional = true

[dev-dependencies]
quickcheck_macros = { version = "1", default-features = false }
quickcheck = { version = "1", default-features = false }

[dev-dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0"
features = ["test"]

[dev-dependencies.radicle-node]
path = "../radicle-node"
version = "0"
features = ["test"]
