[package]
name = "radicle-node"
license = "MIT OR Apache-2.0"
version = "0.2.0"
authors = ["Alexis Sellier <alexis@radicle.xyz>"]
edition = "2021"

[dependencies]
anyhow = { version = "1" }
bloomy = { version = "1.2" }
byteorder = { version = "1" }
chrono = { version = "0.4.0" }
colored = { version = "1.9.0" }
crossbeam-channel = { version = "0.5.6" }
fastrand = { version = "1.8.0" }
git-ref-format = { version = "0", features = ["serde", "macro"] }
lexopt = { version = "0.2.1" }
log = { version = "0.4.17", features = ["std"] }
nakamoto-net = { version = "0.3.0" }
nakamoto-net-poll = { version = "0.3.0" }
nonempty = { version = "0.8.0", features = ["serialize"] }
sqlite = { version = "0.27.0" }
sqlite3-src = { version = "0.4.0", features = ["bundled"] } # Ensures static linking
scrypt = { version = "0.10.0", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tempfile = { version = "3.3.0" }
thiserror = { version = "1" }

[dependencies.radicle]
path = "../radicle"
version = "0.2.0"
features = ["sql"]

[dev-dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0"
features = ["test"]

[dev-dependencies]
radicle = { path = "../radicle", version = "*", features = ["test"] }
quickcheck = { version = "1", default-features = false }
quickcheck_macros = { version = "1", default-features = false }

