[workspace]
members = [
  "radicle",
  "radicle-cob",
  "radicle-cli",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-httpd",
  "radicle-node",
  "radicle-remote-helper",
  "radicle-ssh",
  "radicle-tools",
]
default-members = [
  "radicle",
  "radicle-cob",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-node",
  "radicle-ssh",
  "radicle-remote-helper",
]

[patch.crates-io.nakamoto-net]
git = "https://github.com/cloudhead/nakamoto"
rev = "90cc3eac67aa5cfd5f42cf7cb1e2b155af3214fb"
version = "0.3.0"

[patch.crates-io.nakamoto-net-poll]
git = "https://github.com/cloudhead/nakamoto"
rev = "90cc3eac67aa5cfd5f42cf7cb1e2b155af3214fb"
version = "0.3.0"

[patch.crates-io.cyphernet]
git = "https://github.com/Cyphernet-WG/rust-cyphernet"
rev = "d42c66399dd48f6a757ba63c49d7a9fbaa52c027"
version = "0.1.0"

[patch.crates-io.poll-reactor]
git = "https://github.com/Cyphernet-WG/rust-netservices"
rev = "37acbf6eac18d51853912907f2383e6563efacbb"
version = "0.1.0"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-git"
rev = "d3115a22158c8395705babefdc89049f7510d32d"
